apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safezone.timeServer.basename" . }}
  labels:
    {{- include "safezone.selectorLabels" . | nindent 4 }}
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app: time-server
spec:
  selector:
    matchLabels:
      app: time-server
  template:
    metadata:
      labels:
        {{- include "safezone.selectorLabels" . | nindent 8 }}
        app: time-server
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: time-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: staging
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.redisSecret }}
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.redisSecret }}
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.redisSecret }}
                  key: redis_password
            - name: REDIS_DB
              value: {{ .Values.auth.redisDb | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.service.logLevel | quote }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
