---
apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  selector:
    app: analytics-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: {{ .Values.analyticsAPI.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.dashboard.port }}
