global:
  # REQUIRED: Environment name (e.g., dev, staging, production)
  environment: ""

  ghcr:
    # REQUIRED: Name of the Kubernetes Secret for pulling images from ghcr.io
    imagePullSecret: "" 

  database:
    # REQUIRED: Name of the Kubernetes Secret containing database credentials
    # The secret must include the key `db_url` and `replica_url` (example: postgres://user:password@host:port/dbname)
    # Database reference: https://www.postgresql.org/docs/current/auth-methods.html
    existingSecret: "" 

  # System Redis who stores system-level data such as time configuration and system info
  redis:
    # REQUIRED: System Redis host, default is "localhost"
    # System Redis who stores system-level data such as time configuration and system info
    host: ""

    # REQUIRED: System Redis port, default is 6379
    port: 6379

    # REQUIRED: System Redis database number for system status, default is 0
    statusDB: 0

    # REQUIRED: Name of the Kubernetes Secret containing System Redis credentials
    # The secret must include the key `redis-password`
    # Redis reference: https://redis.io/docs/management/security/security-redis-password/
    existingSecret: "" # Optional: Global Redis secret for all charts

  # main cache (Redis) used by analytics API
  cache:
    # REQUIRED: Name of the Kubernetes Secret containing cache (Redis) credentials
    # The secret must include the key `redis-password`
    # Cache (Redis) reference: https://redis.io/docs/management/security/security-redis-password/
    existingSecret: "" 


# a data analytics API that provides data analytics and dashboard
analyticsAPI:
  # analytics API container configuration
  image: ghcr.io/rebodutch/safezone-analytics-api
  tag: 0.2.1

  # logging configuration
  logLevel: INFO

  # affinity configuration
  affinity: {}

  cache:
    # the interval (in seconds) to poll for cache version updates
    # the cache version is stored in a different redis instance (system redis) than the main cache used by analytics API
    # the cache version will be updated while a simulate event is completed, it is as a cache invalidation mechanism 
    checkVersionInterval: 10