apiVersion: v2
name: timeServer
description: SafeZone Time Server
type: application
version: 0.3.6
appVersion: 0.3.6

dependencies:
- name: safezone-common
  version: 0.3.6
  repository: "file://../../../safezone-common"