apiVersion: v2
name: timeServer
description: SafeZone Time Server
type: application
version: 0.2.1
appVersion: 0.2.1

dependencies:
- name: safezone-common
  version: 0.1.0
  repository: "file://../../../safezone-common"