---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: safezone-db-secrets
  namespace: safezone
spec:
  encryptedData:
    db_url: AgBJ3Y3Rckl9FPvGksMN6of+6WHRZQUa20CkbJ8qge8mYPo+NAm0zJd3G4BI9o/JPdB8/Y/+WRGNwp7XVTLQyEr41s1wEINUiNN8d73h9a6/dAEcs5/xr9f06WYhMmWzCL/KIZ/eG2vCGCWr40Rka1ckh3YNJakh6PYMK2/N1vquEbMMVwLvQioU7ovMp9pgmw7wCJ/yV+mFw5ZtzcF1FV9iX1vcTIyEPp2ePTt8hEUOq6a9C+UWU381ZNDQRc0rt8+q4f4D734jpX4RKRzQLg3VRJpe8ocitTOTzZ6V3h+2LcQxKgOsLDuQMrIAWr57xMdBA2tVOhXqf6oxhxdrAFlG/BDFla/gPjDkEUvdnxgovjLCuHaq1xHgzqMkwOXe65OsEdQ+/1rlzq/g/E94i/Dbk1duhhnrqQeclB/vnNLE7Cey0Jqyu8uBWjCkgANYmZws2CTpl3es96hWqlM7tGE6oV1Rf1Fc83Oi3Oew1LZCzgs7N5pAX+kjJlZUT3uLD1sjfOb0fAiuZVIcdNlTACgiLWNESVVvkDwimZXr1suEgY/8RhN7VXAyRQ7suRbFi/XZL3S9aSvZAg1kLYKbK9co0raZOibPmhB0zVBEq7EP+Wpne0Pl5fIeHH/oZuFF4LJEHMihopmj37wXq7LNXFLT40M2xqRCosgPjVjmnmGtRFKB9RAvZy1E6K9AMw7FqHFAV0u5ZaPCh/jVaS1DxKlAemke679bMR/y5BMcMX5ByAgB/gN9cWN4FtHvuS37jy+EAQIsg0O4Tc3DQt12QfDTo83aM27NZG3oa0bOBNmtpq1BLM4piBQ=
    replicas_url: AgDUpQ2aObNlJ4SY0wD3QWP4328DRvd7cHYfodJXWs2AmUrL8jsK1C7a4kMoiPAVJMc7YqNSuTJG2ankfQcaXHeL3EazYSOW6zFVxTu4RLsDNK7/6m8ldfVt3CLx8EdshPZsroj79ub08Aq5FI4EQ2AtZPAymGUyZgk2WFdeKXoVRDGBhI8Ve24TYQOxGcpE/4kmND/tltTI7kVkERn5dZyp/Kal1yzF4j4W3dXvu05UrxnGF3hrUK+Xrpyu+UrgEEt0J/MIqHlFdshhJ7b8sV6kmYgcCpBBkiuIS5rMY48coNg5LxPmLvISQbR1eXwFBOGG4kCz1FAmN9CKI6x3o1H/4M1IYWaBOLUF8u4eBI0nLSNadbCy30CexmOlM3s67dnt4lNJ4uNxbxfd5jY8NadlCH0ML/Ki1FrbOy5/3ikQ4zapfYjbrXRfu1TozZqVhlvQ32f1za3v+azc5saNqI1qCIQGOXCdylBjd8J1GdTmkuXyc10Xwd5nqFSm+qW4XlIFJq3AqJWkHEHm7uNwHPmniOcVwNWgCi3qo0rplU3VMW1rXzM7F7Lylb/N/rR7wqUllPccNbTlc0JHmvKEvWO8veiFZrmxzeu4rIVgHGN1gIfwh02j9b8tbmrka+7Q7hcN1Sx4r7oYkaNfLVHAO6qG2qVhMdC8E0YefX18OlL6T3M7sb7X3lH+5kiki60ShT5UsxkvC65MUxWZwoE9HmQgu1RU4fTci35wdhVSj5fuv3rFDNw8R+wKrLBZQ9judvrvROkfEDUXWd5lFag0FoBCh5A1snBZYiK4dxsg7p5BIDQ4oWI=
  template:
    metadata:
      creationTimestamp: null
      name: safezone-db-secrets
      namespace: safezone
