# umbrella values for the safezone project
global:
  db:
    dbSecret: safezone-db-secrets
  image:
    repository: ghcr.io/rebodutch
    pullSecret: ghcr-secret

# consumer subchart contains the analytics API and dashboard
consumer:
  analyticsAPI:
    affinity: 
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - laptop-agent
  dashboard:
    affinity: 
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - laptop-agent

# producer subchart contains the simulator and ingestor
producer:
  simulator:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - laptop-agent
  ingestor:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - laptop-agent

# the addons for the safezone project
cliRelay:
  auth:
    authSecret: safezone-auth-secrets
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - laptop-agent

# ingress for the safezone project
ingress:
  enabled: true
  className: traefik
  host: safezone.omh.idv.tw