apiVersion: v2
name: safezone-infra
description: Umbrella chart for SafeZone project at phase infrastructure
type: application
version: 0.2.1
appVersion: 0.2.1

dependencies:
- name: safezone-common
  version: 0.1.0
  repository: "file://../safezone-common"
- name: cliRelay
  version: 0.2.1
  repository: "file://charts/cliRelay"
- name: timeServer
  version: 0.2.1
  repository: "file://charts/timeServer"
- name: cache
  version: 20.13.4
  repository: "file://charts/cache"