apiVersion: v2
name: safezone
description: Umbrella chart for SafeZone project
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: cliRelay
  version: 0.1.0
  repository: "file://charts/cliRelay"
  condition: cliRelay.enabled