cli-relay:
  image:
    pullSecret: ghcr-pull-secret
  auth:
    roleFile: /app/roles.yml
    dbSecret: k3han-db-secrets
    redisSecret: k3han-redis-secrets
    authSecret: safezone-auth-secrets
    cacheSecret: safezone-cache-secrets
  service:
    environment: staging
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values:
                  - always

time-server:
  image:
    pullSecret: ghcr-pull-secret
  auth:
    redisSecret: k3han-redis-secrets
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values:
                  - always
