global:
  environment: staging # preview environment setting should be "staging" (only three options: dev、staging or production)
  ghcr:
    imagePullSecrets: ghcr-pull-secret 
  database:
    existingSecret: k3han-db-secrets
  redis:
    host: valkey-state.safezone-preview.svc.cluster.local
    existingSecret: k3han-redis-secrets
  cache:
    existingSecret: safezone-cache-secrets

cliRelay:
  auth:
    roleFile: /app/roles.yml
    authSecret: safezone-auth-secrets
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values:
                  - always

timeServer:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values:
                  - always

cache:
  auth:
    existingSecret: safezone-cache-secrets
    ## @param auth.existingSecretPasswordKey Password key to be retrieved from existing secret
    ## NOTE: ignored unless `auth.existingSecret` parameter is set

  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: chorde.io/avail
                  operator: In
                  values:
                    - always

ingress:
  className: nginx-public
  host: preview-safezone.omh.idv.tw
  tls:
    secretName: cloudflare-origin-cert
  dashboard:
    path: /dashboard
  cliRelay:
    path: /cli