apiVersion: v2
name: safezone-ui
description: Umbrella chart for SafeZone project
type: application
version: 0.2.1
appVersion: "multi"

dependencies:
- name: safezone-common
  version: 0.1.0
  repository: "file://../safezone-common"
- name: dashboard
  version: 0.2.1
  repository: "file://charts/dashboard"