# -------------------------------
# Redis instance for caching service-layer data (used by APIs, dashboard, etc.)
# Stores high-frequency data such as query results and session cache
# -------------------------------
redis-cache:
   # Override the full name of the Redis cache instance
  fullnameOverride: "safezone-redis-cache" 

  # Customized for this project: standalone Redis without replica
  architecture: standalone
  replica:
    enabled: false
  auth:
    # REQUIRED: Name of the existing Kubernetes Secret containing the Redis password
    # The secret must include the key `redis-password`
    # Reference: https://redis.io/docs/management/security/security-redis-password/
    # If not set, the Bitnami Redis chart will generate a random password automatically
    existingSecret: ""  
  master:
    # @param master.persistence.enabled Enable Redis&reg; master persistence using PVC
    persistence:
      enabled: false # only for cache use cases， set to false to avoid unnecessary disk usage
    affinity: {}  # Optional: Node affinity rules for Redis-cache master pods