---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "safezone.covidSimulator.basename" . }}
  labels:
    {{- include "safezone.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app: covid-simulator
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.simulator.service.port }}
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "safezone.ingestor.basename" . }}
  labels:
    {{- include "safezone.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app: ingestor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.ingestor.service.port }}
      targetPort: 8000
