---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-redis-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgCvT6+dF+Ks56mzTyRXTaHsu0/ZcXQ6+DQ6nBIcFpuGcwsEnDLbMBrbI+Vf91A8cwrLj2WovR3IMZ0Rj6Gro2XZ0n35uTwh6zAtaJg94mp7OshQeXOVk/jbsdyn9syKMLr+ICKZoRVCz52aS/Y7htLTEkdKl6rg13Wg21qYfmgDYPLIEQaFp0BSZdBodrUUDB9iDGC9ELikXkaTh2XiP0KA+n2zeSvazUGob7h5rnyMiIlmUz7CyB3U0MrqIxxu15iMdA6/oezPCct9iUuG0NHVw8C1Vumcm7MUWdmIauWTzdWBpp0tSpMI0xxNdY0e3OxWZDymBsvS6ixMBXFGbRDRLtfte0qnNn7AWRkgklMK+b74GbiGbuwsx0X5QYEtU9aQaavy/OEVYOxrtgcPGwlF1R+ZNpSr/dTCTEGLpNK6i0hLWdGjL/F72GD4aER35irLc91gbmdsnV+BroEqUw40b7eX7SICt7cAjlqXX53CC2opQBI0OVRiv06o01xOoZeO1EO6KCR0ZYPSQcLUEHsOPf0H4dZAwrNPnU1wSNXp82XJM85yxMpwoMCl5GQ+pXdEVhX1PuY2dY2NKs+/VEbDiZfe+A+2VzlpMNGpdCm3JNkQ4+t0s5mz6anfaGnBVZ6erExmiN3BL+dfygidhlNit+9DweHXdzpTXxcuPMQN/lTbGCDzTCqB1j0/oc5VWb4l8XbRpTPBOvL46wt/TYPp
  template:
    metadata:
      name: k3han-redis-secrets
      namespace: safezone-preview
    type: Opaque
