---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    kafka_brokers: AgCg2c19ENgU9yHDQyjuS/VXt1XIYwYsAmKF88O5pL/DjP+Nm3n4PvoCw3RfRFTFNuhmfTYpIyPKyLzCWBclIcLBkaBln8tFwTbEeAt0MlHJ2L0zZQAg3Ff0Szk5HspZyTusl3UPHiZr4RuHDX8/PKOrlguDIC3pUecEYMN2z8XaYGyARE/9znznFhdTri+h1krBP6CeKzocYz2suhWXsrPrbgbL3S0BdnTbFlQiJwLQt6adKbM1hQLPjD6I76yNh/wX4m/etZsIy6WZMwH2Hh8pOljulNnGOw/FxZ2f91RAwCDvAzYEdMM1Zf6H76jZ1Dl8g9I8M/PiY8bY4LOmdk7ayoNxlTJq8Yh9Bb+6kITv/UZ3A+b4RfMhId6PRiPPbP8DBhWliEkmIiZY/NenVfmPAr3DcPl0dsvdckuDfKn8POxfuk9Mnd3Rg8Zm6UK5whWaXESJThPy8nlTTN/ZbvDPfmW35oQOL+Yf4yuq41AsJ3ZyrRRlUnjjtRgVl5mz1TDVONO3sbQ+uc4pNSxcl4ra6X6upym5JvCp1HtMIdMZ8pXNEOYtGtpqOcBYwm0t8yT2iIu9RDA6pluiqYEgPjc0GS3g6f6wEImTRz8o/imGc+w4ywfdY5SphLslx9cyCRAt6O/dwzusA898nztzuGLRNwOImntFVQDsaQBZLnI3xSh87ei4uCCmqP51BqQmRNf+zYv3k29hqPU821YUXrPL2I7H2BaRzll6cflA87PjvmQruX57sv6TdpDVcb5Sevvb7F9TxuKRugpp
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone-preview
    type: Opaque
