---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgBzurGX28/MtKZgvlAGxZ5Osbw8YSZvJsPxE/sCS7A+3z+NaaFamvE0EJr9UsgOm0R+m1wxD31s40IC4s4irLDHnqPgCIYV4kvieIAaoiL+g1DNi8E2ZxHmUwETUVa+EKsp+a8x/RPWMPpkJ+ObyLQOv0ehkOHfb8gDgajHoIRU0WWx8mKjnFqCaaF/RqyKarHEkgntdIOtioLxpffDBmpBHV+hCgEKRdBJmMArvkTCJ6oJXwYPlx98Q6t63XI72nPL5UD5+Kt60ZE8yji4jnkZHGVZem/vLjyH36PMXvFb1ve6LMaozT3ak9BOIl59cLrFZF1ZX+oiAWQx9doFTsvDHRMh2KG2bOCWyltTZnyGdBytgqZaRBjIUeCrktU5TGmfSpbj/OZD5Y98HV6D2agMB6/AcGt3JV7gzhHNPwgRhTqO0ynjuBkkqtfaN3T54gpR6bQf1XVPDq2jhbV+Q0FMjg1dcxCIIsu3ymC8qmd9PYdVqmeU6HsmZjUGmMgXPBi+IxaK08FhcqTFxMicu7xg7hlifhwKGvbM2YICqpuZ+AlD15NHJQj1/iN/kqMD3QrKGVtnlDBMGkoXoHlN45wufKgAZEef2EtgxarT2DpfpU1AOv0y8onnh47PD1ItilS4lZERYS20HajKt9RclnjunA0m6y+t0a8GxLE9mPJ/oQgRrq3MgiPCK1HdhDJi4PH3mtYR8zefpNwB92K64K8w
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone-preview
    type: Opaque
