---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgCdBdpZH2TGJHOIWi8A7w6Aw7J754UvXXvrenzV8/bHBqfRvDtMkQAKSsOjRjvzMe2ImtH6lIhCQFoDxvNOiMkVOv5kO8cjpHlt87qFa4gmUvd/8zORUsN9QL5Gfh3FgfSi6EjaMYZRvjZfu7SNssnSF2k3IdxUdqz3zotIsL1KYIHVwR4lBl6zh2zWH46u9vVcwCp2GJtig79XZ00mgjivfucGlecyc+7DaF66Gl3LVaGgClJxD17mJfhQ3LBLLJjoVo+31FLdr3+sdk9FvRvXUOnYmHue3/A6eIuzYup4H/7JLUHbQ/qt1k1KyCxy8PoDf9V5q0UIkHANDOQNRTkbuaGtEQznVOfTfpRjVJDdQiGsGcALmc8qO1g+/+4cxxQCw9hisIgRSsFV4Xg6T2noZqFgqVd5twFBqS2yCcYLGVX0mQTiyg5NqgnF2CoqWtQ+qI/SkvGWPS7QFrgMmUvwSMsptK9nRh3qzf4i4PsbTjFQh/0zIfO3DPyFu/rxcfpOq0Qpr2wKuGycyjw4gGLpveTAcziZOZ27mriLxo2/WSXbTnDFI16C0Ioq2JoUczLCQB2B7scKzgOdB7MLlOjWnnd0OnjMDx/qBo7021EewA5jq/81JglmNRv70B3wq6+bDseT80Cfz61iwZtEHctT1DIq4POikz/jhPLog5g6umjpnu96atHPjtW48pN1e/AyHq5iJvbqv1is52ynkZUG
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone-preview
    type: Opaque
