---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone-preview
spec:
  encryptedData:
    .dockerconfigjson: AgDWQfCYOM9p9Y81RKsEhyExDH64tvWgLufraBIYbbd5ANEZFcsgAiNgDB3L2S0YvvW803Vm2pGjbW0w2UQKB5jqTLylhRpjYrB8hIh+Hj/R7gLzVn1vUrdnRIZ9/6Ed3w+o0FIS4f/rHZUAO91Ee9XK0Wy3YcWFoUEGzL5SDzZYXLNnHrcEOrbiN7wFoEKQwBW45fPGEp4bSobDHPuxkZfh6rC/4XBoO8iMshwcOLOf1DmWeUam6A6LmQa1AEWq2FG/9QywbdLKtakwE1ccKiLxgAeEMshHa0l+mRfLQSN3LYgJiit9xhJNoUtSB9fabLFXPdm0zbR9LMd7J8rxRWLBKPc9lt93MJMsxJG+20hdaFRgWak2P9RTap8tshSMYNyuB7bDe1xmhytYh34SbHuSjZw436ecq0RI2iDPRhe67BVZMS9HNhyL+dnp2plJf97k00vFg8W6F5L9cKnYlum5B2z6dhLwIAqDsX5jMgns3+D0JTMjmwCY4Y3YHWwu1BGlrKwCAlDG6gqC4boxHaCK7TnMdebVXzeCqQJPIKMttOSGeGiVJYSpi94QqLt4ye0PV3wCcOMOqlPJw3/mQ74BIF5i8SsBC2ax7wN3y3Ek8hBbRB9iUC6c6g6wB+B2eDza80rbNPJ38oLCKZ1Vz9cjzjZqwsg+k1PE8f6emp+09wCDnq7cnCjQW3QLYbwd2ZLWIe5vVi3jkZiq5Enl2N8VSXoSKTUK6bRtNdFoZb1BhySftIuV79humZQgXJlGnYT0oWuiOUDCpbeQZw/T7r6rJAmFC3WGKuW22DTW3CLWupUBV2767NKTRGAm0azWn5FcRBe94G5hzM1yjR9+PRllcX93+EUWB/RdgqdX+r0MuGuaO+U+TESF
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone-preview
    type: kubernetes.io/dockerconfigjson
