---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    rolefile.yaml: AgC4LBghTsoyikn1LH11rhuFsKKT55BQecjY8HmTuw2/iyeWKzSQdlwT7YcWUkU2FZJ4I7hzaf/77Py3Ks4Fl051+RjvGA9XFlX0Bmf303Y+RPayfwM4IMe9/9TfYkpAsE4f0DemTLPReuvh12BmLgAnB0Ce5+stt0ArAtW+v2gbrZSZ2z0kVMdkp4cg0iHefKjOaT69G+9XI7cAQo8tIdczHPP0nzXMyI8m8lOJmiL0xUojQQzTBVeQofBCO+w6y0pElhzPmQ9I6GkXeS2+BgSnOte9dtTfXPqZRpB61IjbHk//39NBuQ3dPaRfpzDrCzpx418K7iwufHEQ8MKzs5GifawvTwyAcwwLNI+u9YOahlI0shHzdO/g4l42TLV8SJmwdSOQzyZM1Sy/4u56OsK2hSK2vLNPvHWrGChdvMP5fD2FMj5giAD9JmPYCeC8/HL2K+8zXVah+fmwxzG9O3RWeGHFvtjkKs7d/Ktec37nbMKLAPRjNs8N1Bbh5v9VenFLiSiI9qmx79kMWk2/kWJFhZnV1zyp/kL6J+oFukoPaIPF9YexXVzz/zrjj16ERK4hDMEmPXnmw9WSAf9qd5fahdKYwJynZkmsmho+iRNn46+jZt2YdLaAe3EfWA+QdiDCq6sI0u+QwN/lWAE0IKcVqWCxDQ+wwvq74yNEBtn6Pu8kdP1Beb9HxypFLz99zEYAlUKP0/nkUNSIVs7nEXRXSrPTGYVXMp8uU8RW+lRknbBZsbaiKaZPbEbi/SMRhT/c1PVcy5EY9g0HpKqAO8E=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone-preview
    type: Opaque
