---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgBCczRv89f38RJTBUqiJgfvJYy6GbBZCR5Vm36mN5qpBl+ehz8buierwquvazAjX0Hh0VNjB3UbNiKgY1lmpYYBp+S7+cy8qDT+W8ENHDStwpcvgmRsHxuDhDn+9RAz3Isa5CVhqMXU27nZ25AX/J/CUsKurVG8PyaUZGa37b8YjdjYsvz7rr+WHwkL/xQdocTemPbMnov6HjTz+iFHe6GtTrQ1ELHKmTX+GOopEDo5NXEmpZNefmH/2Cn7T4JhD4HBH8b9jAJZXYoImcMiuXmA6LCr4grAve18iLkP3X6lsW/FNYIzCfxdK+zmA0cSM6PWLLYYjN5v9sIjv7A372xXZw4mPBC+O6hbIGE+x9KvqmdsHPldYf8nw7f/E3bZp3FMLDi3E6kXeAClMlGM1SoGgx/1YKXhujPCyGNo+VSF6YhP9bodhE5KHXlEGkZlQ5aIzBgUut+EdtkbVGXIFY5SM3OaV65XecHQJ9nd/cUOajCqaVBg+tAusNjFY3u0AUtPEfuutH+1ugOcC//R3NQ27mvX8gMDikn2+R/g0UynKZldFlXe8fCkf40wxlpNUL8VZ7p9ufgFK9pW7/9B9QWzQft9JBwhvi0IwPnlITTDuzMqS05Lf9Yzml4F+eSUMdMY345oAqs1+EYjcFxmuI0vASHlGAeoRgLy+kwDPQcBX6jCv7TKhI0guJxHV+qT4Kod+e55JQyeKc0EPVfjzSXK
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone-preview
    type: Opaque
