---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-redis-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgCMNNleoSe00toQPZra9kr9sSuZUCHznkbNMUwakI93/qZEz3MTqLWHe1MfaA5/aHFSyzIHPnQzl+kjo4Bt87E564TqT9CAHrk70vqCtoi8voMN2r9kOX+ZItcF0uAksdKj4yArw7OLz/XMh57lIEwyPVb/r7H+nWgSEcmwkqBa9LT4csSCydktlgnhB3ldpO3q42ThmCPBdRmsu/YGJYQOirlRBcwjROcctilsS3JQST/Tf9KYLxAsDuLV7/TYonxWKB7lk7fC5VGiLM+7H0q2hQGvHBEPOzZx883NVFoUmkZVbZar5rYjG14jMo+KlijooQIv5zIBKgYFCoqWwMupLjSofqRga7uvVbWSM1PCvsL3tV+yNnUr0PQAfERPoB+kZIZ+38o6MylYZvBJgjqx/vAUDD0YxtGht7oOzwgw7ka5AbbUeKXEPCweOrgXDZMH4LBgry5i4DUynwfwka4yEc1RZ3+dqbk1rauS2npdgPOyNZl+CjHa3cgSOuXLYoVQTPQ9tXY5dBK+Hdubv6G+HG5Rswy1j39ShsebZw2Fb8JMGdpxsXXDXAhZzOPzr+/Hx/2aevjC3VlBfk33MTLgkBAA3JxpOPksiYyKkVgEDOHEuQ50VXU/+3fLwe1VKzMoJYPyqfLriwhjLIe64QCgUv55qieZeYGK3aeLjD32yf4wx2a7JcbYyJH0oom5rIQNlCL4PmgS78rlJPAkcFE4
  template:
    metadata:
      name: k3han-redis-secrets
      namespace: safezone-preview
    type: Opaque
