---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone-preview
spec:
  encryptedData:
    .dockerconfigjson: AgBloGFD4tFIXGbV+ShAZM8Gew7kIPtBMjvm+HYU76An6x+DLfhTW6SyrHkdrEN6DYVegPHSYd0G6iZgecg894CW7szO5QCMJgbL3iu9rsDM6AwshoSggH+tWlwJJOi+5SfFJxio3T6day/7LHK+sbGMwf5Lt1/kXyE3uQqkqhvHEstdxyjEbCEdR6GcUkq0Nb3R4OwB9Cm0H4HaXAA9+jQRmV0gPgCsiYX52cJJhiJKk2YG6Tc2B2YbXpJN+YIZa0SCt8oT0+Tm8q3pIjGruQyMJmANmmhr+p9FIEm8XhY+ckkq0N8lvtxJu02iN/llP8JH2zw28GSHx9wfRXjEIoGbeX5u7aCv1z3lMuPt04Cq/3EftNNr0CDNsd1JUlfeOdBqUd3NbL4MxQrVCKgH1SNhxtFt7V0ay4z2t5I5wlcYVyJu62qCuEHVlPDAjhpSJL1XGJlKQy4hunjxeMy6mOAKl5YTSnaZ1RC1jXGLIJIgZySY61xWX+OAy8lHRPIaUEjWOEL+zj9gB1NEIQkSDSvuurOXgQzuboDznG8RpUf6mmNPJ1j1lBKw4IWAuhHXPwmQiXaG+FTNVv4VNssDrco2lT3IXIEKXU4NyxO2I4ekribcmzaCGrNoQ89sH9xI/vr4QG8pVfkEcrILs62BXRvlWpyLYBRpzuPMaZ5diT/xxW+2ZqyM/wZ1hV3ce2ovfQlb/+SKf/io6GcM5kQMb+f+2ax+NMPtSb139wbGEBtgHy4BkFtu8CpMRqylR0AcebNEVJ7cUazPZRsxsADwOvubZ4at3BP4Usp0B92zgA5092IO7xc8ysAMf2e3TuQYnF5wfVzuzuq8Pa74gVextyg8VcqxN23VA3bWcdYBwnAo2wMh4ewOLGyB
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone-preview
    type: kubernetes.io/dockerconfigjson
