---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    kafka_brokers: AgC0aYOJ7mCrrorpu/oRQb6GZNwhfuuLZ31LW5KQ9doTHsDJqzh7SG9iBmHPuMW5ux8WyYeJaZa63im9YTLLtzEy+naZplXQMlOyn/+65xY1Te31d5+81lpU2Glr3O6S4/ZTBiPWHvyQ4zxE26ujIw5DGaZK97DKC04PeRiWawvbSbVxKPx4+YCUxIcmJYA6Rxm/r8xOYyDAQXZgqnB43n+3ALUPLiVLF5UfJD10EkIIj5AZ+U2E5W8sWAwZqh/zCNtqA7gzma9VedCOBFBuALgr7HujTs7qD7o40EZt7Xz7n/Uax8ZcQncU0CTzScg0XHWWuuHKA9rqzT/tOocENBh7WXIMa+b0RyInqRf4PCzjNKQDsvb8K6zGuEc9irzO9ArrqBkQKsxbpyIlEEw8mjR9F7umMu2/0q7W2pYd/V/gnttZkphTd90gf3BPckzfANi2j1+RDnXy/djCdI+QSigx9aLj/QyQ+IbKrHawldz0qjkKmt1z7wQggS03Hg/842vrlCH7miMlS9Dmx6bPyCl7ZK/FMaAYSCQX6sBeMH3768gWiitasPXKNW2mJ/Vbd0GVoPhrAVL48yaKEcNu1o+diLVjuxgyswpJVVEs2DhyM0hA6/Ny7YicXiWjOew9pTFDBmEkxLFNaDFghcYorcir/O+XZKGyheZJK8k5uILtyFT0CI5Peeguzk0YSqljjEj6UKLSQq/temjryHViKLsjoqi9EKMB9kGwMaSvGA1P5J+84ZIdQ5xVgPrmHxMRyaN9NkuQfH1Qym2O
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone-preview
    type: Opaque
