---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    rolefile.yaml: AgCrMKJVNtBq0Dl+aAFWnYiJkmEXNIsCJGcZCQKzaJZj+pBeA/3Zsi+GMjZnLyvwbLjtKEZg9KBKuiA4YSnao8cayoymlv2MpR1c5ckW5rcYZXIR6P6XozQPlLo/BVDqwTV2iQfmarmv4Q8uSxwIxT0emABim7LPSmcnarV0EJUtp9a+XO4mNaiGPJHs6jZYChZEDbalt/jP8ne/q7do31P2fvrpsU2LCWNuYi4qFfMayppbNNgxFEQWDaFBji9tjjo6Mz8zRlXrA4kWCUTz2jym47KXhly2PH+MaVPQytFudcsAvwQMMQMut8wblNNDRXYzYgYNJ3KQxNOvKPP/rkNVf6k6P6FWaNjnuv0xvlgpVSSoDlYhhmVQVUkgE+HKroKbGxh1TlbKsYMjnaJfqDywGzAg7e9VB0F8Phi9PxRyjEK2rq/CLz5ivAUycPEVD9kj/YBZiIxMxGvLdN3Zihx7It4gWhSmvFTNjOSkB/NLmk69uYkswFglJgOrK454lWozRJcb+WWnQy+lLTnFN+xqJTM6302pYgg9hFXykh5jDXCt3w9NUkdHjLDh15fjNeDj7H9nOhVmS+mopNaY0lEA4xIIvocnxdaf9tUsWBMNyFlgO3sqBu8Im3pWydvvE+l9ASMNZa443jlqdAu9DEUaiYQqLLcrtVGwahYH1v6ekTAHkj1r6zfgaHIRr7uRyHEVMmhEMGgZynEkG398lDzvRYB/WiBOk+QHDet10Nka9KRcGHFgN0UTkdTb8SiwbfPs7VP+zYMn5x3S5ecYGpg=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone-preview
    type: Opaque
