---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone-preview
spec:
  encryptedData:
    .dockerconfigjson: AgAo/JOm8F8a6CJqqi6+obqA6pcDoCaS/4+roQHhmPskHxzeD7styQMXq5oThdvq23giqH/N2o0cxxxB7fZO4wqaTrpBkGSUTXLr10HrN9Pop92XvGTtbshBdH0rwJooEdFEzRRkRx8gZ6wWWPJHJLRnyOaQ70RAvMVRs4IDdFqMCkJoRXsQsvRoyQypCIjb5UX0VFbvEM9kWu8oIAngSiwGkyQSk/dheU/dPwqWXj1PyMN2oozftBdEga2eDIc8JBofPkjunOBzOZnNo+uaNsvNJ2q1UVjXQKYXsn2UZ+HzB7mY6aM998BW8XU0NU/dKvZ9Ex1MjpSVjjCMDZQjP8p++1VtV+/KXBQFUi3n/t3UhVsB7tXwKX2qAG8ELQYdLKMCrmw2bt0uQAgK/syZoeof1SF6hx4t52pDVsH2mibJg1kz/p/Y+6b/uOER0OC8c7Ccr4SNIut7hJVwceLI/j5c5WEarEvrVabSILKB61NeBfQH+D9udD1HAStD25yZAOHgMmcPb82mTkrmkN8Dr5GF22kQef2dBUpyljGbVjBDsgiOIZBmydUUoWlJtN+jiSQExePDh25Q9/PCobgum6rvY6IeFzKVJVyVQQPZ1IEBZtEC1MIrs4DA+tMz17GX9YHUfUQyJ9EDUyzo7h+vCATqs7qnfWB2q10FxcQGRb/2ZuiCr8Cn+vfrgMc99uF3PCYX0ZUcd+5SVcrXmwe+uTR9xrz8C/2egMERCK8/kszdIL+5GkCZHE/Ct4is5U79zjF1cdIi+zbRFXGlgH1yc5LPmnkoTBcbGMtcC6k1UdkbATtgOegY750wnHvRqNXV6iVEBHJex4gmUD/h+SrehIHLu4kCwY1wwwvPMt3I9pCdJyepjbSm7UgK
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone-preview
    type: kubernetes.io/dockerconfigjson
