---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    rolefile.yaml: AgAB+9AcSmQ5QdMbaKxzYayP2FvNn80FtsOVRZdqz5ODrcdJaPtk9SLfC3DrIF0GNzaro9uHUhn1xwJDznr+01VY3icB6gkagniP6NYQVCdJ44MpHsOHwrjwr3z2txJB0Ooyq7NCnX6rI7j/KkjR9/VXnP9YppCoBg7cgb8KSTBou10YZB9pV7MPh6FM4UEfiMuFN4P88/glbBcyvXYe3HYtvGk4B6mk3IVzsw0aYcJma/uyqgzlNpQxRlOBj6wXGo/2CLngSTByYG9aQtAnor6u06SUvGgCYKqVnBY45Pv+J+gBcAa2IJfw/U4AuA2Hcsuq1tftYqKZcSB1IX2xhYXe8QT0FtL3CzpRfT1XlOJou0745STx1E6oHda7Tgm84eQ6hxQ0bgaw+DIlL1FGhccBZVi4xGiNu/ixZfmO8DL/Ed9w22fNmcqHSYiJEQtt26dEmGcunqZzZAlRj+tli4WKn+k6iDXZnobFlWJzhuKwgAeEpE39nXmtLMMy867hKcchdAL42X8Km6YH5Y65Vza4QqEHRYq04RL9R7VvqJZL8Fb/LxkEMQuMn21W3Y2zaILa5tQk4k+NvKAub2MUxUJda8Pb8eLCViTx+xNQQQbQvVIGxWuxUgNeGds9xAuhEds5lqJdz9F6qvj7yPg1CeZ5Q4dAyNx+qeOEBbhzj8w26JKDUH/AyfWzwLEShWaL4klAvRDVF5sBbxKhnet+GbIWl7r5dMaGj60Z4tcftUAQ/uOu2HLXHuyb+1rStS7bLuwJ0/eZ4Oj4vtomFkns6vs=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone-preview
    type: Opaque
