---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-redis-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgBoBre3SoqKq7yJdbXF4d942Wg5kRWVzp8h7nMq4rpDd/WdP0edB8eGuPM4qLEw2jSsL+3TAcK6Ytn4sAj5FgcoSlHHJ3wa6v2G7+qfAHCoDTIqXUQQndMiSqieXpr0nK5wywDtrxMDX3hMjtR2LhpBF7VdVvEldacOdOSDRJwEL+ibqj63oBQWsIg8nGo9N6KKESZz9O2aVWvo72NYwiD0OBBH77B58Ac7IBLBGpf1fUOb65sMgbgZIDM88tn9MDqC2kccLcEg6Hb/6ndQ1NPYQRDtz/JaPAYWyEll4uz+54ebjRoHDoFRjjNFuC+q+7ZiRDABbo/LPYze2BkPc142bLfQNoUsVmu1cAQG55pRB916ZItgkp4duL4ag5bzumKZnofkjXJ+JSZbszVG4lmqx+6JPzx2IfyUs/Pu6rXZE6ObEubaRfjJ7hScXhDuY5JoEgUnYLBCBxsoeEPvUA+AVJcDE6KdQWYzGNXB36sWdzGA9kbIJxT5gTzu2/QDRWXv/FinpQhnEWoiAkZx1vc7ZqDRF7+rw15LlThMT11Wh3U5+D4QPgg6jo293N4QQgvrM68o7djY3PmhSkZ6qcUm/a6t4G28zM6FhigyVrYyEX9FGB1yHAUu6qGFxUvtWMlq+IPwUkNSb53sR6Sr5kQ7hD1i31QS1OFH8AkLUsbdsZeHJHjzqdpz62dxPQiIukc5EPwckrZxT0ScHLBebdOK
  template:
    metadata:
      name: k3han-redis-secrets
      namespace: safezone-preview
    type: Opaque
