---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    kafka_brokers: AgCCv9K6EOqRrGVoyXc9UkppL9HqFOeJ6OTa57xxeIRhqkw3DZ4PRCAyLsKOwu93H8rvfnQ7xF5XeSLanjs5CyedH41hpLSjB/MuhFOW2l9nBfbx2WlciiwOStkf/8XXmxzIXROcYL7nwPzKl13m7z31EBOPb4gS8rvSmCfb/vfhSREQH0oD5dOxPiwXAE2nd65rljJlX2VfTArFBHgoXRuMi7r5wkcmAH6ZGstn9MqYo5vOyMjhaAaFDxEaljxIoDqYATtjzQE3OXGxNuYIw2GShAk+JfYFGUNVDanFNIyzWra8M02CpYFoApJN/SBMYNhT2EPbV5CHfRLkrg0yGg64aDL23LZeFcE/UBV0tBc5LbXqZFu5yLMeDUIfB3qsw8NNYPsG1xZyVN9m+xUYNH5zveyCWh3R2LYPgqUp6mXJjeaeZW9s4xZblZ6I/h9uTVT68xl1vM89E9XY5oMvY1q1EkwJY/jh4ur76M+Dn3YJyGYUnR7aMvZHsINR2JIJM7whyo412z5r4w0kg7NauwyEIOcuv9tlWQ+AaekmXxGAAp+ti7SduXb7KfLGPXOjc+haVk1RMmY/JQQWctk8/TiwUsoIfEIPzDGpegbx3V0cj1i6L4xmObL6Vn6LbrzFH2nml6X2Jczs2jItMX27HbBZ3DNxDvDbRNzhOUrRVf1cR/r/XZ1ABXSD9LVCPnoWG5mxKf2bU5DThouN8qQ+LBEiIR/6nDm1y8pH7DJpPVbjDKWIUyDG6lIEIdHLFi9A0mL+R2froIs3mrtn
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone-preview
    type: Opaque
