apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.simulator.volume.persistentVolumeClaim.claimName }}
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "local-nfs"
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.simulator.volume.persistentVolumeClaim.volumeName }}
  volumeName: {{ .Values.simulator.volume.persistentVolumeClaim.volumeName }}
  {{- end }}
  selector:
    matchLabels:
      app: safezone-simulator
      type: {{ .Values.simulator.volume.persistentVolumeClaim.type | quote }}