---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "safezone.pandemicSimulator.basename" . }}
  labels:
    {{- include "safezone.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app: pandemic-simulator
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "safezone.ingestor.basename" . }}
  labels:
    {{- include "safezone.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app: ingestor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
