apiVersion: v1
kind: PersistentVolume
metadata:
  name: acer-local-1g-1
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
    app: safezone-simulator
    type: smoke-test
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: safezone-preview
    name: simulator-data-pvc
  local:
    path: /mnt/k3s/pv/1g/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - acer-agent
