apiVersion: v1
kind: Service
metadata:
  name: {{ include "cliRelay.svcname" . }}
  labels:
    {{- include "cliRelay.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app: cli-relay
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
