apiVersion: v2
name: safezone
description: Umbrella chart for SafeZone project
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: consumer
  version: 0.1.0
  repository: "file://charts/consumer"
- name: producer
  version: 0.1.0
  repository: "file://charts/producer"
- name: cli-relay
  version: 0.1.0
  repository: "file://charts/cli-relay"