# umbrella values for the safezone project
global:
  db:
    dbSecret: safezone-db-secret

# consumer subchart contains the analytics API and dashboard
consumer:
  analyticsAPI:
    affinity: {}
    port: 8000
  dashboard:
    affinity: {}
    port: 8080

# producer subchart contains the simulator and ingestor
producer:
  simulator:
    affinity: {}
    port: 8000
  ingestor:
    affinity: {}
    port: 8000

# the addon tools for the safezone project
addons:
  # cli-relay is a tool receive the command from admin and bypassing requests to services in safezone
  # and db operations, then return the result to admin
  cli-relay:
    service:
      port: 8000
    enabled: true
    affinity: {}
  # cronjob is a tool for running scheduled tasks
  cronjob:
    enabled: false
    affinity: {}

# ingress for the safezone project
# this ingress is used for the consumer dashboard and cli-relay
ingress:
  enabled: true
  className: traefik
  host: safezone.omh.idv.tw
  
  dashboard:
    path: /dashboard
    port: 8080
  
  cli-relay:
    path: /cli
    port: 8003
