---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone
spec:
  encryptedData:
    rolefile.yaml: AgAaID3peGGJpZByWQUu8RKYaSvuKlfJwyihQp7Wol7033elXiDS7J+9N82PceTHtTM9PDKAOv1qUKxuBsqCOZxK+rxvHnieyFIkNLkOKP1S2SNIBH+rGLFymbgxH3jdKfZtvxXUH8fj69pR36KldF7cbvPrBFovUUwaRCiMHdCbF/cMzEYr83GhNz1sU9Vcy4gQqeqewTDVyeI4nhHb5k+J4lC8qSJmhjhlJwCK5vM7eFRhOe4xL6JOb4UO/xBn9DDWGec14rMsBJWjVPACLg5x9zBoQrBM8EiloJo0xfdJyY2xmRk4lkJzDqxxWSGohNtpeyH9AsHpKzay0zG+5RqSRFEIARdHiNMglUY9g1jAgxezjbw0WDRgfgRMAWuH/aRiob8TQjtTMJIYEUPTc77e1mpyCkKVIQHe16nOsAXN9AuBGW4JWMBjbjRhlPDo41iI+NliSFu8w2MYzPy2sDgFhz/r+8WpMR6bNLUQEkqTPvAauocEVIckatSgBQkXpXHBrlk7CVj09LnffNKwOkgkCJxNOPVgLfjs6alKu8nUh3a5NzBo0lHR0izFZzXqkk0Ymm3apVV6j2YjQcCqI4DMViKg5BDYoEptlyoMnU/LIqSqD7lfjfbvS1vTgf4HDWIZIFKKak4MTy4cLtW/3O3KCu3owSDeAqYR2y6fdgDL7W14PMpemqiKAiJ0Hi3ze7RithVoCD+915EGVz1RDpbH1kX8G7sZhl27eZwE6eFMZijeyw5nLjdCwPElr/cFeF/vF2ve+9tFzgHCV6cOzIc=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone
    type: Opaque
