---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone
spec:
  encryptedData:
    kafka_brokers: AgArfWVIQ7MNA6jcSFvxNdMFuLzRFZFXrl46GmgX0yoCG6HWT4p9CfPaklgYWt2m8ZdqnZraKilXdVjA+R+Uo4eaUa972v8O2/BEmBAApIHxChut+O/Pq3opfVUnelLG5lsX1/se13KtTlGnbKhPsZXWyFZ7CReDckgsKJKVWDwm9fzvu+AcKgTCwh37fzA13VZLTE7gaAfjhdsDf3UmaVoJep/5g6FxUnkdC/Ep7DomnqK1rGrp91ECBauhg6MMidmI4f21jyr/We2AGd04mQE66D0+JqCfqNrnWjA64JiYtqe9qZGmVRAZyHzfOL2+vXFYrLoXn4KNR92zbfIY4l9qqZRVjIooB8CrNFa0XIlyrtGtFWVDGtYTx0gva5sMc817tCoL0PH97n9m5XGbdo3gnSte6osWdjiPrRhG9A+U1vLW2elbVUp9sgF02+rqjZJPw55nBqIZLNUhrJUTfHaMIO74ujwBMGjEnZOlL1ZyoHINLFe8Q8vdn7/B+OVKzrDb+alIpfqAwVInfBl4YqDc6fpDD498rcFcsCOz5WWXInqE2ZNDO/DCCdPnCmZKw8UgfdnDZiFiLB0rTw8al3LZHY4XK1ZxZMHnuktPM9mu2NCknjNkv9BC2poe0u/G+kmHnD1dXGpoTYK8bZEF5BWTR9TyNXFXB1Aj7i9c1P+KXCDVA8/6SKhbjdQii9dB1GJNXeXfprac0nk1ADmNPUXg3H972GM+QrNtgS2LIriRPL4HyHFSk2CeNfUDxPrAXclRIk4cctKmwaGq
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone
    type: Opaque
