---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone
spec:
  encryptedData:
    .dockerconfigjson: AgBP63VgdMFEveLdBycYvqfuXJeUX7ZFY6wIN8la2sn3+7+c0LP+cfmHw1pqvpjzg2z/TAGzj0rIhePSJWliO9xFlCapYeUeF/nZgL8LmGlGnwyuLextUggjYA71xQMh7Y5Pv6/l91LTfhUiaUOmk5+AG7gI/fM0hOfMqOdoM8yUkHPl4kMHzoXIzNFiBW7GohnJAMd17pF2FGvU2GOgcIyUp8U5LcBfcN3g9g9G3qqbNNgrscDrWSRWBHwp5WWUnTCv120C+yuYAVsIY2fyI/fDr0WDTMXkQcsdRbwWY2pm3KKR0y7nBj3VvbexCqdopctzQSrl2HikJgo+ujZgU/Kd2jb52HOpuWQH141zgZKmC9Arp979xx7uAmFFYdLmmolaEYOlTRPARB25Ez6msU4jfaPMQ48KZuGy2177BA3QCdU0wUoiuZDgK2TGOOuBSINrCT5ngK95E/tVUyE8Yq53T4O6Vwfvnz4jRDXgGyfBwMUlnkNHTGh5hw/uKNg+0ZAF2B680WGlZGjYbHksesz9R+t2H2tu2BhWJ7hdvVfZtxK7W1d1RzNCBwAha6UaRD1ALXA/aDvEiFZ24LiJpFim7mDjucRZlMCZeCyp6sBRkgb3F67c8elaiSWKLtDv+KPeQFEVpCZzkN9/nzqdU0bSLUXsPSBQuY9LXf1URCwnyNYvF66Li2NVV+7CtJiQVt1/v1GrEzNXFZ6qU8w9DVXKN2lqh4zT5s2v0X1S3Yr2SGtAV+zSQJVGy3JlOhty2ea2i/dXEkStEGTYmBvALjIbyQeCHSYgBSLf8dIG/utxMrbIkEhb9dLaK3mtQPU6napcyubwBwX6thrFGByfncSPfs1OkxnEA53I5AMnkBO2f8d7AjMZYOO4
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone
    type: kubernetes.io/dockerconfigjson
