apiVersion: batch/v1
kind: Job
metadata:
  name: infra-seed-db-init
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      restartPolicy: Never
      containers:
        - name: cli-db-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔧 Running db init...";
              szcli db init
          env:
            - name: ENVIRONMENT
              value: staging
            - name: RELAY_TIMEOUT
              value: {{ .Values.env.relayTimeout | quote }}
            - name: TOKEN_FILE
              value: {{ .Values.env.tokenFile | quote }}
            - name: RELAY_URL
              valueFrom:
                configMapKeyRef:
                  name: safezone-infra-safezone-config
                  key:  CLI_RELAY_URL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: client_id 
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: client_secret
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: refresh_token