image: 
  repository: ghcr.io/rebodutch/safezone-cli-relay # DO NOT CHANGE unless you fully understand its implications
  tag: 0.2.1 # DO NOT CHANGE unless you fully understand its implications
  pullSecret: "" # REQUIRED: Name of the Kubernetes Secret for pulling images from ghcr.io

commonLabels: {} # Optional: Common labels to be added to all resources  

auth:
  roleFile: "" # REQUIRED: Path to the role file within the container, e.g., /app/roles.example.yml
  authSecret: "" # REQUIRED: Name of the Kubernetes Secret containing Google OAuth credentials
  dbSecret: "" # REQUIRED: Name of the Kubernetes Secret containing database credentials
  redisSecret: "" # REQUIRED: Name of the Kubernetes Secret containing Redis credentials
  cacheSecret: "" # REQUIRED: Name of the Kubernetes Secret containing cache (Redis) credentials

service:
  environment: "" # REQUIRED: Environment setting for the CLI Relay (e.g., development, staging, production)
  logLevel: "info" # Optional: Log level (e.g., debug, info, warn, error)
  
affinity: {} # Optional: Node affinity rules for CLI Relay pods