image: 
  repository: ghcr.io/rebodutch/safezone-cli-relay # DO NOT CHANGE unless you fully understand its implications
  pullSecret: "" # REQUIRED: Name of the Kubernetes Secret for pulling images from ghcr.io
  tag: 0.2.1

auth:
  roleFile: "" # REQUIRED: Path to the role file within the container, e.g., /app/roles.example.yml
  authSecret: "" # REQUIRED: Name of the Kubernetes Secret containing Google OAuth credentials
  dbSecret: "" # REQUIRED: Name of the Kubernetes Secret containing database credentials

service:
  logLevel: DEBUG

affinity: {} # Optional: Node affinity rules for CLI Relay pods