image:
  pullSecret: ghcr-pull-secret
  tag: 0.2.1-daily

auth:
  authSecret: safezone-auth-secrets

env:
  environment: "staging"
  relayTimeout: 300

cronjob:
  enabled: true
  schedule: "0 1 * * *" # UTC 01:00, approx. 09:00 TWN
  script: "staging/daily_simulate.sh"
