analyticsAPI:
  image: safezone_analytics_api:latest
  port: 8000
  affinity: {}

dashboard:
  image: safezone_dashboard:latest
  port: 8080
  env:
    - name: FREEZE_TIME
      value: "2023-04-30"
  affinity: {}

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: safezone.omh.idv.tw
      paths:
        - path: /
          pathType: Prefix
  tls: []
