apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: safezone-seed-cases
spec:
  project: safezone
  source:
    repoURL: https://github.com/SafeChord/SafeZone-Deploy.git
    targetRevision: deploy/0.2.1
    path: helm-charts/safezone-seed
    helm:
      valueFiles:
        - values-staging-cases.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: safezone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true