---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone
spec:
  encryptedData:
    .dockerconfigjson: AgDhq9gSR1wq2gKjumDsN0SL59OkgtfMoywiUwSlHld06Z7xkWGsTdAe6JZLGhdUxEh/Gv2XOnptvJF3PAtWuhhDTD/oysiK6PW0yFy9RGX1lLVYUP5QXxWGfuXM/G+hqdfv3DX28aTlv0ueIh6uBiLU5MabNdKhZCimPofyOwDw2R4YHAUzz239qmmqXd9/c/j2G5op78AVKnbzsyZSJd+KmMfQaqwyV/7oYE2OVUvB/JLAQq/fcUMZduYHoKWki0b6vo7parcKCADA9V0DLx/Em5CphlFQobwEipX+q0YpdFYfHsMRdDHYIi1Uf5DfJAqyC6hB/pGeynqmG7RSDdUtFSqFDq/t+oadept2xvgNo45Xzz9WIvn1/jKNo1oxKh5jKEY2/Eh9BadrMhoKOFzzZo0i5C5uJxZLCyXDnoIn6NG/IvsHSJPygpB2sF6jbym7owOPdxEX12ZES83xLF/onnZybEk3lI4ZtlOn/YoEeJDH04ZhWr+b47cpGCNUXJwrVuUeT9dOIQG0m3J29E26FwBHedbr7v7lXY7b8Y4YJ2nV9JoUNFysye+arEXuPMcBA0RcoQpO2G5ddkjVehsvCTO2UaQeR8KeNLP9jrZCycQoE+oayLBE/pwg6KlmZ6r0pLQQ6T/x8ao70PpHlXj8ufJXM21+sfRHJJPYc9Dd/h11yptIAMV+Kb7jNlugPfoljpnEXWgDX97cW+m3eAGsl67i4/tmKr8ZwkfTVw+iHZ100Mm06D4vaXyno3DU+LA2gUuO4lbCIuqFzx/oE0ae06pgRvSxTymWMuA15wO8GJamSKgQL+3rg/1cQ8qIERg7FlQdKkNwcQR28Asj2lvYGIsSJLNshgSbnO/ju8A55Uq2nTvQYDRJ
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone
    type: kubernetes.io/dockerconfigjson
