---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-redis-secrets
  namespace: safezone
spec:
  encryptedData:
    redis-password: AgDEo7V+oH5BF77HiItb7w86Ox+5BHgBbG+X9liF0wPZ+zApxAoGWYWRxKNDT9T3dMijqhi7OJev/RlUxhMj8+BXwZDHiBz2gEclNQUkd0yC/IvZmB6N/AVuntqe56biJqft68mJIafpSJyn5FIpk8ERfTKHV/59fzmMMo74GVxCXn6XeBu/NMDieBn4uYsIYRS7+TQTGi/zPVo294XSD+vOzCm1QLejO3nGNHlkq0kyrvHTAA6vAxl3fEfUbeaX13wS+ediQWBm5Y1lcCWU5QlTbBHvPBtU87jLTZ4xHU5BeDVPj5BP2ernZCE9RyD/JtsnZtrYdi3bFuy9afLnsnyIRKUv093zphKkPxtGSkIGWyZrVT/XnNu7hfB962XLJfFzGdTH7qgRbTPJbttcsVG7igbmPrDUoXNVhknvY5Rkn44usFVf2vyamybfNv6LYGdEUCMcT80n4B5dhvmTHIuwFExR/GyUrBGosNRArcVsHlDnd7FTf3yELC4ToDrRddFxr/nRiQ28lQOdpWUZToF+q9FYH3bWFWFLbeb68uq7j7gxURgzi1KJuMUWRR5isqJAQ8pKma23M7GRhkweJzRogpsXK0OmuUboBjK02OOKN5RMMYuoZeWUPJHphI36O2/goGKukoN4tWuZDu+ZmnJTMp78NleY402FiYnYp30aX6sYqhCRhxzbko6QI+8Esr8jlOHvaCi6rfnx
  template:
    metadata:
      name: k3han-redis-secrets
      namespace: safezone
    type: Opaque
