---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone
spec:
  encryptedData:
    .dockerconfigjson: AgC+jdqcb4Cf0D7P0tC/hvZVlQ52W5MkXw4B+AvMGH5++JtQbvz+r3phpz0CdAiM0Uggs377ApqC5yVcYmaD4yK+/qDqKfTjoJ/NK/bpcHjUSaWK6NpxrI3QdYN/cCdfCdI7xeHoY6j3RmEIe17Chs5vhOapoodfVBGL+DlyvEUjrv9N2l8b/mH5Zgm/+K/xZ57rovv1u74K+zSUTnDI3T+8Ez+/0gTz2ZhzxrbLvkKObVQt4cLQ/k+RWPgrNlvUi8ZER2OWQYr6bpp4/XHhAJm+LZjs9Ds0frU3bNSyTL37pjh58T5IXkRVW7vZBjiyUzi7aeklH+r9Wi5ThTVIVfu4noSfTxtPXW0NnR0rVfbf1A4RAX5op1cZyBVaLFxZhUpqGhyhFnHTpJx+2pUfSp06CQ7YAqHWnQkukgEneLNdhPi0LGbDkTWgLoIEYHtcsoVvkcqS74OI+ZBO8PXNsNod0HU9R6KdIEkazeuIQe2FuDW1fqoxlGbeW344jxVhQmpp+noRxTM1YeUkUX9U0nigGqrxENHY787M6VN7VINuSaMM1ukG76VUENnd/9FnTDJG2ovrpCPdPgoTKTCmreSsM01fFx3lPnyX+Eu8bOoJSEuXfDXNaYjvn0p1I3SUob7dNr5F6QikBC3tkUJzIhht5wq/OtB5SwgJ+QCtOxihyb9SqDAPVfg2yAM1Fom/p+igyc/w6e2/P3eTNi2kpAuV6AA0G2QYCdtnOZ1po/wHJxvmBSY1ZUh3nfu5NzWD21EqB8SGZb2At+vhSL28X/9nXRH8Kp+bu5q3jQGjaFbHe6yF/pIV8rr5VpwLuu2kOEkxhuSIAd+ihI5gwxaqMvfYbtAEHKOP5ngSWD8pZAcwODWwBvNpsU44
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone
    type: kubernetes.io/dockerconfigjson
