---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone
spec:
  encryptedData:
    kafka_brokers: AgCjTLu9li+y1l56s1ZhqNEa/1NvdYetG/otwOm6m7bQiAsIw5rQByaV4SX4FaQlE2QcFdroMzXPt5RAs3z2aoFQ/tADD/ru4OHoJQHFupluEamIpGpaDRGbgc/IbtanRZgAh7g0/wzDI9ryL0X1LaNOhkD20qL+Jh/WY6q3tlsMNyzI30aWAFHyVOQCxBrW8LO4cGaF/LHy/SSU76xDPZnRfBgrBA5hJop2LrJmqnkJP5LMqGNTMpiOTXW6cBkwcpUHaSlCkiry8iGkgfF/Md9pgn+gqqiJEZC9mqJApQ9vMcesujEuceAAXAswzATf+jkHwnlwAjovnRUC+RFrAt4Sp8GldkTHbelrr1bSqONlQOc5vp+TiV8aCjFfwOnWDNmVhByBy4kneScAsXPRNXJZr7iIYmiMQ3qkUoLL9Q/pbn3UfN1OeBz2uzW9WEwl3ZtqHfvhlO4HW1wKdPE0BYS15rM+UVcXmwo828egiCcWHKNM0Q1T1r2GDZzU4JcPICZcHBUGpnKmXR1xHcsrIq6JaUvXigkfYb4w4+OQnTcoiB96dZw66biOnL+1f+9Lt+S6LcKLNy2rTpZBBOp3gLcGIPzBjQCJ93jncebIsTyRE43BL4s19Pj2MIiRDPzStPOlKs726KEmMy0ZaJT3f7DiybaqsIrOqa+eY9fQfaGPSZXM1rPvj/vB2JIOW8JJvgBeLUIc6gqGMwn/TQjpY6q5EemGU8BQJYeeceT/kzcv59OIcjTqQFze2q7IgtzUb5qmuoo4YKluC5Mz
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone
    type: Opaque
