---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: safezone
spec:
  encryptedData:
    .dockerconfigjson: AgDWaIjRu/hgVRAB6XOzFPAnNUGhkJpQMKu4cXa6Ui9z8M3nBZe6yCqZ2H6tQ7qr4YSx3Zd2VNQt0Uc46EVeB9T8JmMWV485Pcx09xz6rOU6/pJdwVIe2zw42BALf4FMcvbla/xb5q8g+c63Iu3D4mux7SPkE+LcTpobHJ8nzdjMzA9CYx/1rfceBTGIH9dtm/TIXLjhwZhwKzDjBmrv2crR9U8fw9YxXcFdeUelcQ//DjCZgjXoKux9LZ1NT/0M5+uSz1d54/ZiRFfE946SifYke5WgGSwh0C4zJaKDMGHy49WDPw/LxFAW+wqAFJVhD0ZunMuCa+kTkCTt9RB4SKLw85nPDEOCPk7mX1WAHzLklRKo97sONrIQlOaX5xGi12EN9vvrPNdHqoVNjfDSpqe45SDJYqQq3ipijDAvErnGHK2C8WalPf438y93ly5HhC3i8Sipgr3DLwlrGxhaz2CCzs3Clli4NVy+uKBc41VNmKMPxwtxgWXqBadsbZxJ7C1IBfAQaw+J/OGZqlLA6EYtZ3uHSeIxjqHv5pIL+GWChkfIThEZGTTTpMv9rvsEMBR3lKguSqn2quDibhclW1j+Hcs2qTKg//3Di0ONbFSmF8a75mfiGaDAudOG/ZY8CjysehOyY9C3VUaxN/QaOg5aIyWaYt+A3aleT9FqNL7DOvA+FYO9f7aTFMQsBzBCA+DxCrLEfjK8j8L2nZLozKcq9hJEk+SNboUcZmoE3wkcZbD7qcVV3p8tQ94F8G9mKxDekSaU5nznZdx7B3jM08hE2ugz1SkDv0F+pz/XvJJuQOjOoZgWTQFDv2dQvBJgcV+J65vTMnAPh59HF+cm7bZmxtDOADuOTOXQhGwEj366P4zmFcrHrUM3
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: safezone
    type: kubernetes.io/dockerconfigjson
