---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone
spec:
  encryptedData:
    redis-password: AgCGh8JLLe57/uCsvgupi/4PccoFkGMDioayF6d8Ox3vW5vrh0KhSdGmkMSAQca2zXl4U4ymym03O3FRAEosbFxtm1qWq/yXGtdpHV0sPV3+v9/XJb3XBvtCntWhk2vmdJqkuXy2Y90KAMo8Me+HFvpmWV/ffeXWlik44zLGKdQNSWoDMZ9HOfND90H4hyViiBEZ9MWfK7Z1jFy7n3bnJsb1Ta0pdz17mVkzIh4TmQg5fvqUbzTW1TNy66R+PJn1GaUZG16irQY9nBLx+9PmKl7UThD5SvKSxnoytwkiYGm+HPva8r+eNdBflROjuoAyHgTvFePPNLg0ZijVCVZZ470mKue+IYTYPdkCN4PFxhCIru0YTw4XJF3UX9XvQumww+7tuiMqmrusCHQy1lMLl6KfHRFe7iDnw/Yyk3dUA7q6WmaW/keMp3jDhM1wHtQqveMAHeCk8++ABgOvQ2DSNf1EofraVtF/qrSvbJQdVYrjT5Pl7LGkJLpcwGdWFethhtIYa5Uu4NXyXr6p9SpknkOzrbnxH/VjpK5Q17vC6k0IYWNm2pCuiMUwI9K0YkcgwV9QwvNlknQsZLBFxZvut+T0o9c/qPgfjQXYBhWUmE2oOGs1lgFMfdtFhGp55ME57zWeHkz/jEJotl8YAjIf7oxAMhGMc4I22JgAWZR9d1Qm9qyBGRdK5YmaNaKqqsa3BlJ7UXORcHH0ut3yPdYmV1tc
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone
    type: Opaque
