---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-redis-secrets
  namespace: safezone
spec:
  encryptedData:
    redis-password: AgAUc6+b7o45LPQEf08BMi/LfmjB5YjLZuZ91eGRdMapOVpItgGFW5vnhng5b6ZTaaGK6irrUjdK4eqYLXmVlReD8ZxDHxkhfUDa7pfSeOnCTWD63u782tuZdkLJiAJwZ8FptyJbSsfa+uYvvGx0P0hi2aoPzpGOXTHhSOyI/4ODuaPS5ghgZ5S5ErToCSnzjREscLeQZMX/3PWru7fKWLpdeApuHSf2SiX1+oqEhqVl3PIt1oBIovrAboFBZijsxi68tMISUYG5EXzfjb05E0CqICj9JTlUbcXDhKuq0FmR72xU/3TGY1n69OzdX9dpmExNqovKX+EuW4uFqhnz7txMgBDoL1p+5OSnv+I/yegtVsI6IztSP/3CpUlALuzEAoZia2ApBvkAY3Eq1DCHanv84dgO+ir2mgXCBzaRJu4TBdH5TTN/ECQ3JQm3ZUBuC1sSLsiue+iVJXCVEwLpX2uiJOMvVR/7PcHePHLvSZAxTKEBbxzKVhN6UFq/juRxCpmObb43PQVG2lu8d13FVeIdDkXu3oczi4+02I3q4YofIXsjpMGk431od38j27DUwGAbT2hF3N5QlGwL31IJHFiivJ0Cv8bBgEgcgyUYXPLl6TjRwHhCiPCzKTBp2a3nJ4QTqoEysO8t9g9oLQTG5oVfq63qmxjt/hFMDSD4wtTz8eH0VZHCDHCfm+E7djK5BJuGDUOv5SUszkYx
  template:
    metadata:
      name: k3han-redis-secrets
      namespace: safezone
    type: Opaque
