---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone
spec:
  encryptedData:
    redis-password: AgAB7P7uZ2QaSN3SKpWHp+lGr6KNJu3vUNDYp/3WJHofixuSpJ6EHaiO0s/Ft1Sflc5dJc5t5lqAgrSBTgryqpy05LxePfgcCIF3ImBPz8+8PZWSP3XRFVnlx2M6n7zZymnnQ3lIls1qulNzEbrsMpjMovlNEdLCwa0wQjCtUIGmiqLWbpJ/FF9XkMGAmXrRwKp9fIq6Jso+59UBhnSGWWrJmd5vLTQaDNB1QO8hb3iixLaYAyHCpuAJNISszG42OXs3k46eQfHdNFgd2AtjTYTZK5VjUrPbE0HGp0oC965xD67iXioIKqREr5og1oYj3UaMgp4L0AjvOakHXjjFC3y6ZupwVXujXnGp9D0tG4xAcAbcZZhLtG0VMkavcyw9xqCCEUHLIfrxKJ3/97yismVlg5PCs5/7U7jVG7vf8QDcqbzwyoGFxMmUFf9HuS/KuenxO7nhSm9ha30BdXPqrMw80pR4piZqVl3wYer7S/bkHGzShDa08tgqSvlFfSXzwtXdYUzX+346VfvWbSprX4IBBPhSWGsunmhbC2o5XRcyA0zn3UCeUY45+CWvq6HVgIgQkfRlk/b2qTT0f5vFUziSfAeD7+GnykbyD007awzjIcb90s0VZfVsZBpBtRnx5gJqEyXMBrpVJ4j2dmiotgwq1EHyV5Xt3rp3+3onQARk0EgoZoJB+W3qJjL1yu4d97aD/Bb6GYz+bk8Lk0S2WDcg
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone
    type: Opaque
