---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone
spec:
  encryptedData:
    kafka_brokers: AgBhdcY6L3LgqMhH3lp+WAYiuKHrY60nbFGfwnL0c80rVOz1IWl5WJ7oVXzL0io6GtxaYjq+L8+gljBeFdL8JC5YD1mjTI5kx+orCjXQVZ0GUorGOQ18k/N8x2qcCzp73z9oVk7joYDJOAheSD/OozlhEpE5gs8LirDjl2cJXUU+uFZaQlixMnmrLTCVtaFhN3MiB8TY0ohvNZkZ8iOtkqhCEIc8w6C85FXXzBzt+lg36vQfV0mMoXE2auHtbLcYaCyWg6i6FwKopBKnFUuXc/we7yQUzzewDoXg5Xx1GKytwi2mkswD5YkO7YXfK6G62B1hhhyf8xJ4Uzu4Iwy60BkSIsBLp6+e44ouO+kMfZUr/75i/Cjtxl07AIxXkARGBkcaPpqdyGmV1urAU/SHov1qjisvyhACkG/gFvQlDd0++0Lj70kTwA4e4lR/HsDEV8tNGdw/8v32qZNsDp8yagJHvvMSozAbU3SNguh6WnhY9pdyhJGGMY9fWwUJv+1Ibk0cr26z0BYg1NhL/k2QzleQmcj8LZ6GwtXwlvCk9LxGytEnUbOKdSooKvP9ZbtUZWAffqEEqNlr9QjY9HboWJg5sddIzUlPtam3QlkvRuQqfNTwHP+ZL8le1dBcOC4JfW0paXDhbgNrWGX4sXXmTpuVIK0wjKKLBitTtckv1otnLPm3T6OIF+D+CuTE1tvUJJKYacVBrrprjmIf0W+XQROUhRLvOoKctV7J8HqjXT3Hk9/c7EHw3p1KgSQF8bgwKsnrWPliHBO651T2
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone
    type: Opaque
