---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone
spec:
  encryptedData:
    rolefile.yaml: AgBwFhuBadN8hzJdBjpnF2NcSrjSOT60f8kzOng6dHon3fn4U4bISo4sVlLM45ky7chKeeK+qMMfX+uNk4ccEssUkSzsGhZd74a/buz5sOOZ+dWIZbGRKkN8p/S0H9elhrz1+Vo858qP/BBiSJNta473uN6If4fGbxT1rI5pHurcpjU/Z51W1yHWZZSWJPk7CkcqZz/MCVv1RPhj2Fs4KnrP4sQiS4ibBtKb2TrF4YSmQHFzA3hCe5B0O23edGdr5EPBwX09m4w8Hvnq0ep3loQRS4d2+5HfxcUb23UhGmxxOiTFzh2Q+W+N6R3wv0KR3CoFf/6evN1yIlNyN1S4vwPgMBvsIX2YUv1Ba80XG8TQ0V/qbQx4T5LY4yyNyhg4srYf+xrfsY3+OyIwLT9fLADZ6DruyK07DkGCqW1s809Kbxb8sABFwIBESfc1wIhc9E7vFTPdTiTezUa4Nnmkt5JRIXE8Y1nRoegnHxqn8i1NoXyhsuzJGND8GRFtt2mhNkrvHNUAXIQo8vphcrkYlWSAchWz3prm5XL21DO8K9aE6o6v9hFVnJgjYJPAvGbBW1jf+4aTM+u2Sx5vv37uFnyEBTqoWg/sZPNcgW4F8YpCMQVWBcWEshwdKEz6nBCHrkIQhsPaHbsHEDtTEN4rVP2wO9cIsCbx4PHigGCVzxtGJ096s4f8dkOLwTDPbsyNMRnuK1y9liIeFxPLMhOKjewCb966mL66c0IhZqfgRbQWT2gHeWN6MGQZ0TdSBY7MdGYhGtT2JkJYD3V2AUcbQZI=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone
    type: Opaque
