---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-redis-secrets
  namespace: safezone
spec:
  encryptedData:
    redis-password: AgAHq2tnOIEZNKFS67p+H7nacPSmZUXYJrgsQbNE9GTIGIfy6azf2P4N2Jh+j9wqSXxM1BgZcJ0mYuq7BKjYRFTZivuYNX7UCqhchVcGJ2TyBDCwApD6yuhONK6UrmLhp1ucrIUK0unC1c0lEcGz835mgCQ9cWKu+L/1prebbCcD9Qv8F6lyf8M5S5qAwAuZNSSKDwWCm7JHvu9oWiPFsiCtrOjpe7uR+T09wQ9N2Tp7lpIVC56rLjhrGcQVRxmshNPbF16icrR90bJg8Rx9UsRl5xevLz10uuNN12wwZOUolS2vTbfZJr/982oqOiUhgqdXdMbbQ0rHNjK0CWHX2f6c4MRAYWGyTVQ9sBiTDNPVx3I0L97Va06Qt0+rCPHcHy04dl+1gkVwqARUap4OFeFivVKOTIkHkhJuF2KRKYghXnAWvBGasgIzVYMahwImTk30u+MMZ9wuF4I0syU/nbdw7Byltdk75TwZsekvkWt6VtJfMx6fveLVgCOsL39IYarfstAz62umWX5kW88gtSyPi2L7U0qybv4zrAoCRePXoNX7X1tMcxhUOHIZgrMCHODKTbJXOZfj9k6zXVMfCH4eTRVpF8FDkEsML1N3u1dpLSn22/PX8lKf/6DIESR34olPUpMAY9rI+toDvHWfeM16Pd5aWwWzQkrqRwVxYpXULYIwr1/bbyFXfhopSPbqTyDqNtDtV7Umu9Ch
  template:
    metadata:
      name: k3han-redis-secrets
      namespace: safezone
    type: Opaque
