---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3han-kafka-secrets
  namespace: safezone
spec:
  encryptedData:
    kafka_brokers: AgCf54v/bpoUUB1aZMfKLeXL4TjPrARQVQCABDT15PxE/IdNgvDog6eh+uoyxgiIuhFxX1mBI1VAWAqJmLxwRtmzVjDqgnf164jV+2jp+DnEdCI6lmTg+Gr13SI2s1uyTRPAhGpYv+VPLr/PkZ62Z3AlWh2pUMcVir3MCjhux/I/qucJboh14CIiBSE6+BTyJeoiXz5fJuI/OOTCrsxSEailN1z1XdLgSixMmqVvLX+Pp0RSvKyBvZ8lJnd3W8fSJq4KwxD5uRh/fp8N5vH0qpPmdXW1urlsbRfvRH2qUh1xfygdr4Q3+romt01u6FyH5OGHXqa57X7QbyY5I8JskmkjBvnE0wnjlMv2poOCR6EUipihply28Es1fl9e4/fHf1WJ4VNOdNDEyCpaLkp114cslPGuvMe/oMIqq0TiaTxFNBl5BPFhjY95Wi97ZCYIpW8mdOa5c2YS6d8jOyFdSChklTmr2nsAuEAn+mY5L4QP1WsMyVyQtTzgszwBC3iZkAkYrSP8pfU1qZeKaS/zPcm89BVf0VvpxebxynWehA2uqgZqy9V5e44dCpGCYFspEc/2xYyksa2bOMFEd0vtrOrJRYgi/kW1CRelwlLufi/ig40KcYihFPXQo1WC4NmnCqVo+Hx8hao5ZrqoHUWpWftioStAl/dEbbc4F4uVWQrUYcHoakzw+k3tdQj9APB1rUFzaYZLhyUtnYJHFm+TaBbjgoQxMOH0FZHYSH4EfjbxARdzO/PnChvLhkVTDDiQ//R7zfHk2oL1Mbr2
  template:
    metadata:
      name: k3han-kafka-secrets
      namespace: safezone
    type: Opaque
