---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone
spec:
  encryptedData:
    rolefile.yaml: AgAJ7yy15j4jY8VBiPQT/zbs42gOPBCznbSnhOJOTf75ulOaPTIvHNMTIDdgh1ngRHEzMJK93jPQ+Kh1+GhYeSVR8951SrmfTXkQJYFr0oEvbBQYr63OtPlWx2BcD9hWhCxrAZH44AOUJRJFLac9zZfz3Va4VrueH4B2NaHgyLvGq1N4aNVLx6yOBzUjPMTJXD29bb2zQO03SXd+NekgKCPMQdy45A6Jod2aa7Y5S1j137nj1znuY+RAbJZzX3+Yf4BMRd0JNRM0NH9c99hBENsVn3t548BHGqB8BGpp9mci6brI6VxkRjit5pPOYyddVUiNumIzdQcPTGFIGhx0o9UfaCUDxITPTCiijE3HLaqN+CsS+9R31XJNa58VOJD/Dott2opoUuORIAjBxDw3o1G63cs1BsrKcWCCnq/+ln7HHzlxd4JH26bTv0BOGAX0d+GQzWzw6ZWT5LpbBzRRHfWiFoCMI2E/87T2eQuxROVSwsGt9c+NSw4++0+cIwzw2lzv53jAjC1/W9YOUDxlYR2ugd2q07ciBGsctpn3AVRjZb+a6ZuOJHOr3vcqomKel8Uu0+DzrE9MhVN1xuqmdGsbPxp62xfgb+7IvmUvWWr11+89iXGKKrmBPnM6q5ZRRB62LNJ7f5SBraTfGIkdQpj5I0F8Qduxl0b/8/d0pgopBz0MfA96dkl6SZ4ucQxcbeDGO1bgyF55d2T7sJ5JeinlOO+qfiDw59QWn7lcpfMKmFV9dDATtTxMclIhTJTkspYd8WD6fjs4vzFRlfu117c=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone
    type: Opaque
