---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone
spec:
  encryptedData:
    redis-password: AgCtLRMQBRG0gnZnD6y0z3i6QTYU6RgDkcwZJTpbLhw8O9T2WZalSYgwkBR/KSmbcHlGmx9OXcmxirDB64plJu/vDDADrycadW+r5TBbw8EEe/tkptM8OWbGPDVg86vmCosWTo1VNlly3wOV0Z+6s0kgbZExT04o1HVNI57CyWocNPWWIYfNyvNP69RJJDoq/M2DcfCJ/+oCUW5XfhaCwt/eoskqG+kjHtOF39jslgJNzLIIglRwtF1VWcp+PB7cnSZLM4jnH5/p9D7I2GYrkyitNsLt2182qR61kjsff7dR//OXDHFzAiC5XHRLp0JpYlq0l3t+ywtsa/9Z0hxuDoWuohFcVXk1x4i1QPPZG5dYjnrm9NMXBSry6NrSFPH8oOgWTYuAZt9nO9T48TCkooaIhGXfpgGsVFrIQTdAIkfBN93II/J3EZ36osUGnLmwJtpUib7VQFUnU6mhyATgsouOsxS0bbr3TsXV6bNK795myk0EcwfGxeNd8MsYWezqwXt4drJg1T7e0Wuqr7wmdcVCstfdYZMj5+ZWssbWa2jgtq4xYGoE6WYOG7LLYIYXMUamANrvXL7zTVl81y3kF8dFFkksIavyXkxf+JVFBQNpqhAUNEHiMu5HzHkuHRG2zQKPdruq2QYrRZuuvUOfSeCXjTVonxdBL8Jk6z6dBdZqV3J/5wfcnsq+0w/TSwKgBHekp36Ui6FYR/Qdqe5uXYj2
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone
    type: Opaque
