---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone
spec:
  encryptedData:
    rolefile.yaml: AgBsMbA8Fo7IzcZqV8s6GY/fw+fUlC9VHsPoPqtAV2X0Kdto7z8YM3Ml2Cjkfwoy/r96vTCpHH33NCe5TZ336katAJDERtHPvFxmCPLuf0XAHbzKpX/6tIyYggzAlUF3Iztt+rsiGFj7J67HQ3LfnVeMR2FXIb0fkychDrddRUnggUJDXYTlVPW/k/3qIzs441VCi+Z+TDRQkeW4jBVsiCF7RbcEvXNbN6C2kBju+Xu1aBQGlGSVKWTjAi7GBuJ0qqc+irzKgk+MN+n+YY+zuGjloup/csAZjzo5Z/3eqME1fdgUGgXdpEaJhp2hG6ndmdBMxRyTkKBMvveiPRWGwUmu4k6KmBPWb2PiTyETlVoA15HdVTHYGOE6X3bBiKt9/+x0MBvFkYw0i+KT17NltAFT3urPqNDoAnTxBy0yvzRwn1ThQXvdPM8lFeIdY+OeuOY8vpda+QUNM2Trl/ms4F1K/grXhprTQYCWhBhPd7C3ahxce+tLS1/d5jtulwSDhKjw00iwtFXB+8osLvlYUERc4k0J1gbgqlAesDJfEtExsCEAqoQJ8I0aWJjxrOF5P2klTVXH0YjP8u0HOLmHr1eUbx6R/H7S1jRawLMqz3hSzhdy0OVNV1hOwa3PgEtkddFZCVLyi+8Hw7VEXE02gTpP3VHkzeVb38Cxk9k70+S4Ak+CkDzNWtUADGdqduTmpFXG1vHOtt1WtDxAztY0njd1ZbUhpPgzibX1jJ0vw26E3UV1WzT+rSBcnMECBmR4Ys2ICBO0wzMla2Ad7kTVwVE=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone
    type: Opaque
