---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgCiWLWQwyUWcupoVO7ipggjx75qawGi/PlIxUKJPHAugRS93P7qXYRJ4SWeqz/mVUGPRh1i7p40bx81dC35futzKXlElt6YpgMfYIYBl1B9dmr0w9psdhGA+XvZvXDAFzxSlBNLAqMLFCL7o3KpMK3cNhW6rmgQpp9Hfn8tL/HR+bTVIBBlAP1arb/NplENIITB6Vm5kINgcID5Ib81MmrgHgAuspE+RGt2H/NAeKsSPJcuzFRQqRS5y39Bh7CgQqSGc8QHAemcBA+QT4rdJQjLa0/y+9Jyb1PdV5YMtsVOuah7BhtxDVgzxFDKdXOzcIVLnL8LY47kRarctWE9YliEwgRL+1eInAuaD660kUVFB1S3EVqYXEHnDHhJtWYlr8595pGStVDgkur0htV93Us+Knz44nnhpG0pfxQ6+SzeEcxY8spHoZaW2ScMBjLsUjpOWOP2v39lE6XDlddQw+myB9Q68icLpR7c2xyikfT7/M7rBqqIbKU/cwli/lrQbKqJRPARk2UZEAGNgZmtpxhHHcSJwEo/YJ0I/bz6b7IoDGL5Bw6xKZObEeDeDVY4cFpt/lhO2OMDF+iJ8ZoKH1SUmB2SpyvVFtVHaM5ocVl8oSsyTC91DC36Z0trkpQYVyu+iXb/JwyrheOvAbPHQ9bkUlEEXDSuSed9qfEEkdx3cXd1SdbVHl6gcWj3nHCzAJDvIXntUKpSC0/h
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: safezone-preview
