---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-cache-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    redis-password: AgAhCJy1IDHNi6hGYSi0qSwqHHfX7cRUnkfyToK0R0OMBFu/FyInp/LeIEfMcWlOy/Ty4yp02IVMrXU8PhPJaZO/oakr+q+ZuaQQQvO3IPA5SVLWsbk6eiTkfNHHq9vl6b435YLrBUbTzR0XDfSffq/M9941FAZ1+9BjCSmrBT+bLw+jkjOuy0Ex7zm8rnXCvvriJpjlvCBcybiiMAsPtOc7GuRPup4Ux/1bLtqdeztvYa8plAWZt4WsdHk46NwFhoJHCQK+IamzWYOJbjQpx7ktg2KHd5C+nKknb/QLOhx5Zt1NXUIvtEVIsgMBQfC1E//oQTthz7w63i+9hcHwf+NAAxd8ZzAQZS3WImq7qoehcEOsNIU7hyBp1tZVXIsS14Ca7H0ykaAso8S7vlicO1by+GyIJsLOPssNoamUVDhRVkQqh5RlDN4zfhcfgPRAF92ezYU8pic/U0jqgzJziKpo6GoKV312tsbaVrvUS/Za14AzA+KqqZxEJ7umk1nRZpec9IF6A6PyO3ZQjFUaAo9BC7K+2m38K9JltiS0w5/PIZvRkc3UJeNdBko57CX3xVA+TIQgm3xT4TYfPE8CtnOiwlOgiTKuL6CxM1wvBSnm/0h0T1ud9kyP8OQU/6b4fNRdBYTFskDJUDHkwXJtaeMSIerJJhkoQAuLnC+RpN5CcEUONui0X66lGEF70u5UFmuoYrlqkPQJOLrzs7VsgKo2
  template:
    metadata:
      name: safezone-cache-secrets
      namespace: safezone-preview
    type: Opaque
