---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: safezone-role-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    rolefile.yaml: AgCEaRmNI3Et65/p0N4Qxzvykm6HlskBOA8OsuDddWTS1xv2QpcBnKoi1ANTaXdfZbcr0ulCGLIHrNeH/K3UP6lUk5IeUouZKcoabynzGdvSA90bYV+UDysKL+fJkOBiWO7sWYBTsXmTi2G37gjKVPQbzvtMpzH7sPkQF0ebDXUMCPpMMDX+nLIwhhxEnNgYRNXcGI1mBkHjv68WRqtd1te5BTtbT864pj+gAhVR1RYleXVxktBhRR29j6WLvSCJ9eMBw0k5y1xougZmQG5xG8Ni+Ns3jWW8lNpCPCBGUOmt0KBl3ZPhrGyVY0WrJCZ2b3mPTn8jUH5P7ER1Y9o8J5Wz6HnhOrOla72YLbmReQ1gSkCwItvljEQhyf1d/j/B/pUAKrJTmXB0RRPG3Cr+o07YSjYTOfTXFYchAzZOKE09lOPXxpTPwkz75r38WstlsT+bVBVWj0FloNlgJXJ2vanBSsdfVTr9x8Cl87o1EECpcWTWs0IqTwj2I9p5e8k+LvwvzwS4KGE3VQrBFoP+jHalzt05yFjN9RV/ubpRH4Ry1DQuueltJJ5iumgccQahNZ0F/iJuDNy76z1KuEoW4ASinXMe8WRHWiAafa93iTnVsThvhvCNluHxqoqQVrOBZjoSBnVBdJVVoPhK/AxEY/lBH7QNVE29X9SWCsGjwYyP0pQnO/Uh4mx6ylHPsW9wfY5zPcnaECK4zhMZ1WEz5t2GrzCwnyxVGolJI/fgOitJcF3vAWaJ8C41z4iumLUNNW9C0eKdlWjBFVdiGG1sz5M=
  template:
    metadata:
      name: safezone-role-secrets
      namespace: safezone-preview
    type: Opaque
