apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "safezone.selectorLabels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      restartPolicy: Never
      containers:
        - name: {{ .Values.job.name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: 
            - bash
            - "/scripts/{{ .Values.job.script }}"
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
              readOnly: true
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env.environment | quote }}
            - name: RELAY_TIMEOUT
              value: {{ .Values.env.relayTimeout | quote }}
            - name: TOKEN_FILE
              value: {{ .Values.env.tokenFile | quote }}
            - name: RELAY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fullname" . }}-config
                  key:  CLI_RELAY_URL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: client_id 
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: client_secret
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: refresh_token
      volumes:
        - name: scripts-volume
          configMap:
            name: safezone-job-scripts
            defaultMode: 0755