apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-relay
  labels:
    {{- include "cliRelay.selectorLabels" . | nindent 4 }}
    app: cli-relay
spec:
  selector:
    matchLabels:
      app: cli-relay
  template:
    metadata:
      labels:
        {{- include "cliRelay.selectorLabels" . | nindent 8 }}
        app: cli-relay
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: cli-relay
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: staging
            # db_secret connection settings
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.dbSecret }}
                  key: db_url
            - name: REPLICA_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.dbSecret }}
                  key: replica_url
            # auth_secret settings
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.authSecret }}
                  key: client_id 
            # configMap connection settings
            - name: SIMULATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "safezone.fullname" . }}-config
                  key: SIMULATOR_URL
            - name: INGESTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "safezone.fullname" . }}-config
                  key: INGESTOR_URL
            - name: ANALYTICS_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "safezone.fullname" . }}-config
                  key: ANALYTICS_API_URL
            - name: DASHBOARD_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "safezone.fullname" . }}-config
                  key: DASHBOARD_URL
            - name: MKDOC_URL
              value: "http://mkdocs:8000"
            - name: TIME_SERVER_URL
              value: "http://time-server:8000"
            - name: REDIS_HOST
              value: redis
            # role file settings
            - name: ROLE_FILE
              value: {{ .Values.auth.roleFile | quote }}
            # default app settings
            - name: SERVICE_VERSION
              value: {{ .Values.image.tag | quote }}   
            - name: SERVICE_PORT
              value: {{ .Values.service.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.service.logLevel | quote }}
          # mounts for role file
          volumeMounts:
            - name: rolefile
              mountPath: {{ .Values.auth.roleFile | quote }}
              subPath: rolefile.yaml
      volumes:
        - name: rolefile
          secret:
            secretName: safezone-role-secrets
            items:
              - key: rolefile.yaml
                path: rolefile.yaml
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
