---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: safezone-role-secrets
  namespace: safezone-preview
spec:
  encryptedData:
    rolefile.yaml: AgA+kqAoRe2WK0Hbj4a1U0ra56wveCwNSqgi+AVrTQmOQD/mPS7RMRXQncc8zMwVWOt2f68fmJjL9I1yd7p6PSendOJTY0daybDe6yt3NE+EA6ZNVnAOjmGjJCildcGQSfph7XwMQ82+I9eo+RrM8LXSbpVeZ4iHzgmw+EP5UhPqFr+wXRhwo2GlL88anQCyYemd3urXyqad4DGgaELrCHGIHM096wdA7j94cpqyyCLPXVxN2pdYdLKg1mAB0+g0zdIBPHKTO07EiPAzsGmOkUAjN+vVhiKqN+Rsi9QaZidMkAI87ZKXBm1m/hs1F3qzSiGxyqZbgHhdmcwmrJeUKnFP2kjVLjb4L0BAsnZJqdV78IU/o9R7M4x+CObVOw/LbO74htjvu5j+H0J8FeS8rQRcLJ5toSC0C9pxZo1MYL5CIHiTSLUGTYV0wFy/EoViAHS7IKBHbaugXi70NUISwDSxowrICDfkVBysbnTStSrPVEohYa4d/xJk+SUjff1X67VYYV6scvDXtMetMxNvuL5NsXkthTL0msNbAU6zZtz6+KJKGTyBz5fl4u2025s+mj+f6gwBgplh9ye/V3jF35iQ/22uK/b0kjLhcau68YAxLk4Ezz9w4oFJiYXYk5gX8CdD/2I8SQ0hpMmsaVe/0X5tR/fHe7cC5zwcTlTDh6BnymPQvQsUAQogqQzfk/d4etL1JfOTTZ2QbuQH1/4/Ulf62t8Wu0427kTWxJ2L/WtASBdrCif+CzHyvv8eiYVOPJZkHlweZIwp3NjdTazgy+4=
  template:
    metadata:
      creationTimestamp: null
      name: safezone-role-secrets
      namespace: safezone-preview
    type: Opaque
