# to avoid permission issues when using volumes
volumePermissions:
  enabled: true

# change security protocol to PLAINTEXT(disable TLS and SASL authentication)
# only for testing or development environment
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

# controller is also a broker
controller:
  # the number of controller nodes have to be an odd number (1, 3, 5, ...) for voting algorithm
  replicaCount: 1

  # to avoid kafka autocreate topics with too big replication factor
  extraConfig: |
    offsets.topic.replication.factor=1

  # the resource preset should be medium or higher，else you may encounter OOMKilled issue
  resourcesPreset: "medium"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/tier
                operator: In
                values:
                  - medium
              - key: chorde.io/region
                operator: In
                values:
                  - tw
  # disable persistence for preview environment
  persistence:
    enabled: false