apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: safezone-db
  namespace: safezone-preview
spec:
  name: safezone
  owner: safezone
  databaseReclaimPolicy: retain
  cluster:
    name: db-primary
