name: workflow to deploy preview infrastructure to safezone-preview k8s cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          recursive: true
        
      - name: build low privilege kube config
        run: |
          set -euo pipefail
          echo "Building low privilege kubeconfig for github action"
          bash bootstrap/scripts/gen-kubeconfig.sh safezone-preview
      
      - name: set kubeconfig env to new config
        run: echo "KUBECONFIG=kubeconfig-safezone-preview.yaml" >> $GITHUB_ENV

      - name: Check K8s context
        run: kubectl config get-contexts
       
      - name: Install preview infra - redis
        run: |
          set -euo pipefail
          echo "Installing preview infra - redis"
          bash deploy/preview/infras/redis/install.sh
      
      - name: Install preview infra - postgresql
        run: |
          set -euo pipefail
          echo "Installing preview infra - postgresql"
          bash deploy/preview/infras/postgresql/install.sh

      - name: Install preview infra - kafka
        run: |
          set -euo pipefail
          echo "Installing preview infra - kafka"
          bash deploy/preview/infras/kafka/install.sh
      
      # cleanup      
      - name: Clean up kubeconfig
        if: always()
        run: rm -f kubeconfig-safezone-preview.yaml
